/**
 * v1.9.7: Auto-generated embedded skill summary for Claude Desktop zero-click enforcement.
 *
 * Generated by: scripts/generate-embedded-skills.mjs
 * Source: skills/fmcp-intent-router/SKILL.md, skills/fmcp-screen-orchestrator/SKILL.md, skills/figma-canvas-ops/SKILL.md, skills/fmcp-screen-recipes/SKILL.md, skills/fmcp-project-rules/SKILL.md
 *
 * DO NOT EDIT MANUALLY. Run `npm run generate:embedded-skills` to regenerate.
 * This file is regenerated on prepublishOnly hook before npm publish.
 *
 * Generated: 2026-04-21T13:08:57.193Z
 * Total estimated tokens: 12940
 */

export const EMBEDDED_SKILLS_SUMMARY = `<!-- fmcp-intent-router (3123 tokens) -->
---
name: fmcp-intent-router
description: F-MCP ile ilgili herhangi bir kullanıcı talebinin ilk giriş noktası. Kullanıcının niyetini analiz eder, hangi hedef SKILL'in çalıştırılacağına karar verir, o SKILL için gereken eksik input'ları tek turda toplar, özet+onay alır ve ondan sonra hedef SKILL'i çalıştırır. "figma", "ekran oluştur", "tasarım yap", "component üret", "DS denetle", "token sync", "kod üret", "design system" gibi her F-MCP-tetiklemesiyle aktive olur. Claude hiçbir figma_* yazma tool'u çalıştırmadan ÖNCE bu protokolü uygulamak zorundadır.
metadata:
  mcp-server: user-figma-mcp-bridge
  version: 1.8.1
  priority: 100
  phase: entry-gate
  personas:
    - designer
    - uidev
    - designops
---

# F-MCP Intent Router — Universal Entry Gate

## Neden Var?

F-MCP Bridge'in 20+ SKILL'i var. Her biri farklı bir iş yapar (ekran oluşturma, denetim, kütüphane inşası, vb.) ve her biri farklı input'lar ister. Claude kullanıcı "figma'da ekran yap" dediğinde:

1. Hangi SKILL lazım? (\`generate-figma-screen\` mi \`generate-figma-library\` mi?)
2. Hangi bilgiler eksik? (device? DS? benchmark? içerik bölümleri?)
3. Kullanıcı ne onay verdi?

Bu SKILL bu üç soruyu **upstream** çözer. Claude intent'i netleştirmeden hiçbir \`figma_execute\`, \`figma_create_frame\`, \`figma_clone_screen_to_device\` çalıştırmaz. "Hızlı ve doğru" kuralı: yanlış varsayım yapmaktansa 1 soru sormak her zaman daha hızlıdır.

## Protokol (9 Adım — v1.9.1+)

Kullanıcı F-MCP ile ilgili herhangi bir talep yaptığında Claude bu 9 adımı SIRAYLA uygular. Hiçbir adım atlanmaz.

### 🚨 Adım 0 — DS GATE + BLANK FILE CHECK (v1.9.7+ MUTLAK İLK KAPI)

**Herhangi bir intent analysis veya figma_* tool çağrısından ÖNCE:**

1. \`figma_get_status\` çağır — plugin bağlı mı, response'ta \`_bootstrap\` varsa direktifleri OKU (v1.9.7)
2. \`.claude/design-systems/active-ds.md\` dosyasını oku
3. \`Status:\` alanını kontrol et:
   - **\`✅ Aktif\`** → DS net, Blank File Sub-Check'e geç (madde 5)
   - **\`❌ Henüz seçilmedi\`** VEYA dosya yok → kullanıcıya DS sorusu sor (madde 4)
4. **DS Sorusu (klasik):** "Aktif bir design system belirlenmemiş. Hangi DS ile ilerlemek istersiniz? (örn. Material / Apple HIG / Tailwind UI / kendi library'niz)"

5. **BLANK FILE SUB-CHECK (v1.9.7, ZORUNLU):** \`figma_get_design_system_summary\` çağır.
   - \`components === 0 && componentSets === 0 && variableCollections.length === 0\` ise **BOŞ DOSYA** tespit edildi.
   - \`_nextStep: "BLANK_FILE_DIALOG_REQUIRED"\` response'ta görünüyorsa, **kullanıcıya 4 seçenek sun** (AskUserQuestion tek call, 4 option):
     \`\`\`
     Q: "Bu dosyada henüz Design System yok. Nasıl ilerleyelim?"
     (a) Team library import — "Hangi library? Örn. Material 3, iOS HIG, Tailwind UI, veya kendi library'niz"
     (b) Mini DS kur otomatik — figma_create_mini_ds tool'u çağrılır (12 color + 8 sizing + 3 text style + Button/Input/Card)
     (c) Referans DS kopyala — "Material 3 template / iOS HIG template"
     (d) DS'siz ilerle — linter tolerant mode, hardcoded değerler kabul (explicit acceptance)
     \`\`\`
   - **Seçim yapılmadan \`figma_execute createFrame\` YASAK.** Claude ham createFrame denerse plugin \`_DESIGN_SYSTEM_VIOLATIONS_BLOCKING\` flag'i döndürür, retry zorunlu olur.
   - Kullanıcı "(b)" derse Claude \`figma_create_mini_ds({ primaryColor, fontFamily, name })\` tek tool çağrısı yapar, sonra ekran üretimine geçer.
   - Kullanıcı "(a)" derse Claude \`figma_get_library_variables(libraryName)\` ile listeleme yapar, seçenek sunar.

   **⚠️ v1.9.9+ (G26c — Token Setup Öneri):** DS seçili VE component cache boşsa VE \`FIGMA_REST_TOKEN\` env yoksa Claude kullanıcıya **tek özet soruda** 3 yol önerir:

   > "Component discovery hızlandırma yolları:
   >  (1) **Hızlı:** Figma Assets panel'den 1 Button + 1 NavigationTopBar sürükle Page X'e, ben oradan mainComponent.key alırım (Hybrid Quick-Start)
   >  (2) **Otonom:** \`FIGMA_REST_TOKEN\` setup et (\`/setup-rest-token\` komutu), tüm component'leri REST ile çekerim (Rule 24.1)
   >  (3) **Bekle:** \`figma_search_components\` ile instance scan yapayım (~30-60sn, Rule 24.2)"

   Kullanıcı seçer → ilgili path: (1) G26b Hybrid Quick-Start, (2) \`/setup-rest-token\` + Rule 24.1, (3) G19 Step 3.1 cache populate.

6. Seçim sonrası \`active-ds.md\`'yi güncelle (\`Status: ✅ Aktif\`, \`Primary Library: <isim>\`), sonra Adım 1'e geç.

7. **Multi-Library Parse (v1.9.8+):** \`active-ds.md\`'de **"Secondary Libraries"** bölümü varsa parse et:
   - Tabloda 1+ satır varsa, her library için \`~/.claude/data/fcm-ds/<file-key>/\` dizinini listele (cache mevcut mu kontrol).
   - Eksik cache varsa kullanıcıya bildir: "Secondary library \`<X>\` için cache yok — \`/ds-sync <X>\` veya \`/add-library\` ile populate edin."
   - User-local \`~/.claude/data/fcm-ds/active.md\` v2 multi-library schema'sı (Primary + Secondary liste) destekleniyor — eski single-key format da geriye uyumlu.

**Neden bu kadar katı:**
- DS belirsizken \`figma_search_assets\`, \`figma_get_file_data\`, \`figma_get_library_variables\` çağırmak = kullanıcının istemediği library'leri enumere etmek = **token israfı + UX bozulması**
- Test geçmişinde gözlenen hata: benchmark Figma dosyasının 24+ library component'i enumere edildi, sonra "hangi DS?" soruldu. **Bu sıra YASAK.**

**Bu adımda çağrılabilen tek Figma tool'u:**
- ✅ \`figma_get_status()\` — plugin bağlantı kontrolü, DS bağımsız
- **Başka HİÇBİR figma_* YASAK.** \`figma_get_file_data\`, \`figma_search_assets\`, \`figma_search_components\`, \`figma_get_library_variables\`, \`figma_get_variables\`, \`figma_get_styles\` — **hepsi YASAK** ta ki Adım 0 geçilene kadar.

---

### Adım 1 — Intent Analysis

Kullanıcı talebini oku. Anahtar kelimeleri tara:

| Kullanıcı ifadesi | Olası SKILL adayı |
|---|---|
| "ekran yap", "tasarım oluştur", "ui çiz", "UI'ı Figma'ya aktar", "landing page", "mobil ekran" | \`generate-figma-screen\` |
| "DS hizala", "SUI'ye uygula", "design system uygula", "token'lara bağla" | \`apply-figma-design-system\` |
| "denet", "audit", "DS sağlığı", "token bağlı mı", "ne kadar DS uyumlu" | \`audit-figma-design-system\` |
| "kütüphane yap", "component set üret", "DS kütüphane inşa" | \`generate-figma-library\` |
| "Figma'dan kod üret", "implement design", "SwiftUI/Compose/React kodu" | \`implement-design\` |
| "kod ↔ figma eşleştir", "Code Connect", "design mapping" | \`code-design-mapper\` |
| "görsel karşılaştır", "visual diff", "QA screenshot" | \`visual-qa-compare\` |
| "token sync", "design tokens export", "CSS/Swift/Kotlin token" | \`design-token-pipeline\` |
| "figjam diyagram", "flowchart", "mind map" | \`figjam-diagram-builder\` |
| "ekran özeti", "analiz et", "ne içeriyor" | \`figma-screen-analyzer\` |
| "accessibility", "a11y", "WCAG", "contrast check" | \`figma-a11y-audit\` |
| "drift", "kod/tasarım sapması", "out of sync" | \`design-drift-detector\` |
| "UX copy", "microcopy", "buton metni", "empty state" | \`ux-copy-guidance\` |
| "bu görselden ilham al", "şu resim gibi", "link'teki tasarımdan", "dribbble/behance", "benchmark'tan varyasyon" | \`inspiration-intake\` → \`generate-figma-screen\` |
| "prototip bağla", "ekranları bağla", "prototype connections", "flow oluştur", "navigasyon kur", "animasyon ekle", "interaction ekle", "geçiş animasyonu", "scroll behavior" | \`figma-prototype-flow\` |

**Not (v1.8.3+):** \`inspiration-intake\` bir **ön-işleme** skill'idir. Kullanıcı bir Figma benchmark linki, internet görsel linki veya sohbete yüklenmiş görsel ile gelirse önce bu skill çalıştırılır (structural_intent JSON üretir, DEĞER çıkarmaz), sonra çıktısı \`generate-figma-screen\`'in \`reference_benchmark\` parametresine beslenir. v1.8.2 build-from-scratch kuralı ile tam uyumludur — clone değil, inspiration.

Mode tespiti:
- Figma URL pattern (\`figma.com/file/...?node-id=\`) → \`inspiration-intake\` (source_type: figma_url)
- Dribbble/Behance/genel HTTP URL → \`inspiration-intake\` (source_type: image_url, WebFetch fallback'li)
- Kullanıcı mesajında görsel attachment → \`inspiration-intake\` (source_type: image_uploaded)

### Adım 2 — State Files Check

Claude her seferinde üç state dosyasını okur:

\`\`\`
1. .claude/design-systems/active-ds.md
   → Aktif DS belirtilmiş mi? (örn "❖ SUI")

2. .claude/design-systems/last-intent.md
   → Son tamamlanan intent nedir? (device, ds, skill, inputs)

3. .claude/design-systems/intent-history.md
   → Son 5 intent nedir? (LRU)
\`\`\`

Bu dosyalar Claude'un "öncekiyle aynı mı?" sorusu sormasını sağlar.

**⚠️ v1.9.9+ Tool Budget Disiplini (G23 — Defensive Exploration Yasağı):**

- ✅ 3 state dosyasını **TEK \`Read Multiple Files\`** çağrısında aç. Ayrı ayrı \`Read Text File\` çağrıları YASAK.
- ✅ Cache dizinlerini (\`.claude/design-systems/\`, \`~/.claude/data/fcm-ds/\`) **tek \`List Directory\`** ile gör. Sequential alt-dizin traversal (A → A/B → A/B/C) YASAK — tek recursive list + \`Read Multiple Files\` ile gerekli dosyalar.

**Red flag patterns (BLOCKING — Adım 6 özetine geç, discovery'yi durdur):**
- Aynı dizin **2+ kez** list edilirse → defensive exploration → budget exhaustion riski
- Aynı dosya **2+ kez** read edilirse → state yeterince bilgi veriyor, yeterli
- \`figma_get_*\` + \`figma_search_*\` toplam 8+ çağrı (discovery-counter WARN threshold) → **uretime gec**

Claude bu pattern'lerden birini tespit ederse, eksik input varsa Adım 6 özet + onay'a geç; yoksa Adım 7 execute'a geç. **Daha fazla keşif YASAK.**

### Adım 3b — Approach Karar Mantığı (v1.8.2+)

Target skill \`generate-figma-screen\` ise, **yaklaşım ayrımı** yap.
Kullanıcının cümlesinde şu keyword'leri ara ve \`approach\` input'unu doldur:

| Keyword | Yaklaşım | Tool Önerisi |
|---|---|---|
| "alternatif", "varyasyon", "farklı", "yeni", "tasarla", "redesign", "iyileştir" | \`build-from-scratch\` ⭐ | \`figma_execute\` + Step 5, **\`figma_clone_screen_to_device\` KULLANMA** |
| "aynı ekranı X device'a migrate et", "boyut değiştir", "iPhone 13→17", "klonla" | \`clone-to-device\` | \`figma_clone_screen_to_device\` |
| "mevcut ekranı DS'ye hizala", "tokenize et", "tokens bind et" | \`apply-ds-to-existing\` | \`apply-figma-design-system\` SKILL |
| Hiçbiri net değil | **Kullanıcıya sor** | — |

**⭐ ÖNEMLİ:** Eğer kullanıcı "3 alternatif" veya "varyasyon" derse, \`approach = build-from-scratch\` **DEFAULT**'tur. \`figma_clone_screen_to_device\` tool'u **ASLA önerilmez**. Clone tool'u kopyalama yaparken benchmark'ın **mevcut yanlışlıklarını** (hardcoded rectangle, missing token binding, non-responsive layout) kopyalar. Bu kullanıcının istediği **gerçek varyasyon yaratmaz**.

Eğer \`approach = build-from-scratch\` ise, Claude'un akış haritası:
\`\`\`
figma_search_assets ile SUI bileşenlerini bul
  ↓
figma_get_library_variables ile DS token key'lerini topla
  ↓
figma_execute ile bölüm bölüm inşa et:
  - figma.createFrame() + layoutMode + padding (variable binding)
  - importComponentByKeyAsync + createInstance (DS instance'lar)
  - setBoundVariableForPaint (fills token bind)
  - setBoundVariable (padding/itemSpacing/cornerRadius token bind)
  - importStyleByKeyAsync + setTextStyleIdAsync (text style bind)
  - appendChild sonrası layoutSizingHorizontal/Vertical = FILL
  ↓
figma_validate_screen ile skor kontrolü (≥80)
\`\`\`

**Özet + Onay ekranında göster:**
\`\`\`
📋 Yaklaşım: build-from-scratch ⭐
 Bu kullanıcının "alternatif tasarım" isteğine uygun doğru yol.
 Clone tool kullanılmayacak. Her alternatif sıfırdan SUI bileşenleriyle inşa edilecek.
 Benchmark (139:xxx) sadece ilham kaynağı — kopyalanmayacak.
\`\`\`

**⚠️ v1.9.9+ Approach Otomatik Parse (G25):**

Eğer \`reference_benchmark\` input dolu ise (görsel upload, Figma URL veya node ID), \`approach\` **otomatik belirlenir** — kullanıcıya "A 1:1 mı B referans mı?" **SORMA**:

| Reference tipi | Approach | Neden |
|---|---|---|
| Figma node ID (aynı DS) | \`clone-to-device\` | Birebir kopya, sadece device preset değişir |
| Figma node ID (farklı DS) | \`build-from-scratch + DS rebind\` | Yapı aynı, tokens yeni DS'e bağlanır |
| Upload görsel (harici chat'ten) | \`build-from-scratch + reference override\` | İlham referans, content/layout override (G20 Recipe Content Override) |
| URL (Figma dışı, dribbble vb.) | \`build-from-scratch + reference override\` | İlham, yapı mantıklı ihtimal |

Tablodan seç, Adım 6 özetine direkt yaz (örn. "Yaklaşım: build-from-scratch + reference override").

**Override:** Kullanıcı explicit "birebir kopyala" / "klonla" / "aynısı olsun" derse \`clone-to-device\`'a override. Explicit "referans al" / "ilham" / "değiştir" derse \`build-from-scratch + reference override\`.

### Adım 3 — Decide Target Skill

Adım 1'deki keyword eşleşmesi + Adım 2'deki state bilgisi → tek bir SKILL seç.

**Karar mantığı:**

\`\`\`

---

<!-- fmcp-screen-orchestrator (3403 tokens) -->
### Ortak Protokol

1. **Skill Registry** açık — tahmin yasak, sezgisel Read() yasak
2. **Intent Routing** — belirsiz → Read fmcp-intent-router
3. **Cheap-First** — \`depth=1\`, \`verbosity="summary"\`, screenshot sadece onay kapısında, ≤5 execute
4. **Cache-First** — \`.claude/design-systems/<lib>/\` cache'i API'den ÖNCE oku
5. **Onay Kapıları** — approach / destructive / evolution / 3. audit fail
6. **Self-Audit** — \`figma_validate_screen(nodeId, minScore=80)\` ZORUNLU
7. **Skill Evolution** — iki aşamalı onay + \`# DRAFT — PENDING APPROVAL\` banner
8. **Türkçe Raporlama** — metrik bloğu zorunlu

### Skill Registry

| Skill | Trigger | Common case? |
|---|---|---|
| \`fmcp-intent-router\` | Belirsiz intent | Sadece belirsizlikte |
| \`inspiration-intake\` | image/figma_benchmark | Sadece bu modlarda |
| \`generate-figma-screen\` | Net screen creation | HER ZAMAN (ana motor) |
| \`figma-canvas-ops\` | Her figma_execute öncesi | HER ZAMAN (pre-flight) |
| \`fmcp-screen-recipes\` | Fast Path match | Sadece Fast Path'te |
| \`apply-figma-design-system\` | Mevcut ekranı DS'ye hizala | Sadece remediation |

### Adım -1 — Live DS Discovery (v3.2+ MUTLAK İLK ADIM, cache-free, no library files open required)

**Prensip değişikliği (v3.2+):** Lokal cache bağımlılığı kaldırıldı. Agent Figma'dan **anlık** okur. **Ve artık library file'larının plugin'de açık olması da GEREKMEZ** — REST API ile uzaktan enumerate edilir.

**Discovery fallback zinciri (agent sırayla dener):**

\`\`\`
Component enumeration:

A. Plugin live scan (library file açıksa — en hızlı)
   figma_list_connected_files → SUI/Mobil/S-Icons bağlıysa
   figma_enumerate_library_components(libraryName) → live
   (Her library için ayrı call)

B. REST API enumeration (library file açık OLMASA bile çalışır — DEFAULT)
   figma_enumerate_published_components(libraryFileKey)
   - Requires: figma_set_rest_token ile ayarlanmış REST token
   - Library file'ları açmaya gerek yok; sadece target file açık olsun
   - Library file key'leri kullanıcıdan ilk sefer alınır (bkz aşağı)

Variable enumeration:

figma_get_library_variables(libraryName=...)
  - teamLibrary API kullanır, her zaman LIVE çalışır
  - Library file açık olmasa bile target file'dan çağrılabilir
  - v3.2+ birincil variable keşif yolu
\`\`\`

**Library file key'lerini nasıl öğrenir?**

Agent kullanıcıdan SADECE 1 KEZ bir session içinde library URL'lerini ister:

> *"SUI library'lerin Figma URL'lerini verir misin (tek mesajda, her birini ayrı satır)?*
> *❖ SUI: https://figma.com/design/XXX/...*
> *❖ SUI Mobil: https://figma.com/design/YYY/...*
> *🙂 S-Icons: https://figma.com/design/ZZZ/..."*

Kullanıcı yapıştırır → agent URL'den \`libraryFileKey\` çıkarır (figma.com/design/\`<KEY>\`/ pattern) → session boyunca hatırlar. Bir sonraki prompt'ta aynı URL'leri tekrar isteme. **Lokal dosyaya yazma — session-scoped state.**

**REST token gereksinimi:**

\`figma_enumerate_published_components\` REST kullanır — bir defa \`figma_set_rest_token\` ile ayarlanmalı. Token yoksa agent talimatı verir:

> *"REST path için FIGMA_REST_TOKEN lazım. Bir kez \`figma_set_rest_token\` ile ayarla (Figma → Settings → Personal access token), sonra devam edelim."*

**Öncelik:** Plugin path (A) daha hızlı ama library file açık olmayı gerektirir. Default olarak REST path (B) kullan — kullanıcı library file açmak zorunda değil. Eğer library file zaten bağlıysa (figma_list_connected_files döndürüyorsa) plugin path'i tercih et.

**Cache tool'ları (DEPRECATED v3.2+):**
- \`figma_resolve_active_ds\`, \`figma_get_library_components\`, \`figma_get_library_tokens\` — backward compat için kalır ama kullanım önerilmez. Cache stale olma riski yüksek, Figma sürekli değişiyor.
- Özel offline veya hızlı Pareto subset senaryoları için tercih edilebilir.

**Yeni keşif akışının YASAKları:**
- Local cache dosyasına (\`~/.claude/data/fcm-ds/...\`) bakma, hatta okuma — live path kullan
- Cache subset'e güvenip missing component olduğunda hemen fallback'e düşmek — önce LIVE enumerate'i deneyip gerçek durumu gör
- "Cache'te yok" diye pes etme — library file subscribe + enumerate yeterli

**⚠️ CACHE KAPSAM SINIRI (v3.1+ MUTLAK — text styles + mode swap):**

Cache SADECE variable key'leri (renk/spacing/radius) ve component key'leri içerir. Text styles ve mode ID'leri için **farklı yollar** gerekir — bunları REST API ile çekmeye çalışma, cache miss değil, **mimari olarak başka kaynak**:

**1. Text styles (typography) → SEED INSTANCE + \`findAll(TEXT)\` + \`getStyleByIdAsync\`:**

SUI remote library'dir; \`getLocalTextStylesAsync()\` 0 döner. Canonical pattern \`fmcp-screen-recipes\` **Adım 1.6**'dadır — orchestrator bu adımı çağırır, kod duplicate etmez:

\`\`\`js
// Adım A: Sayfa boşsa (Page 4 senaryosu) seed instance — componentKey cache'ten
const seedInst = (await figma.importComponentByKeyAsync(navTopBarKey)).createInstance();
figma.currentPage.appendChild(seedInst);

// Adım B: findAll(TEXT) → her textStyleId için getStyleByIdAsync
// → styleMap (id/name/fontSize/fontName) + roleMap (display/title/body/caption/button)
// → fontFamilies = unique style.fontName.family listesi
// (Tam kod fmcp-screen-recipes Adım 1.6'da)

// Adım C: seedInst.remove() ile temizle (veya ekranın parçası olacaksa tut)
\`\`\`

Sonuç: \`roleMap[role].id\` → \`setTextStyleIdAsync(id)\`, \`fontFamilies[0]\` → \`loadFontAsync({family})\`.

YASAK:
- \`getLocalTextStylesAsync()\` — remote library styles'ı dönmez, SUI'de 0 döner
- \`figma_rest_api /v1/files/<consumer_file>/styles\` — tüketici file'da style metadata yok
- Hardcoded \`family: "Inter"\` — Adım 1.6'dan dönen \`fontFamilies[0]\` kullan (SUI için: \`SHBGrotesk\`)

**2. Dark variant — VARSAYILAN: TEK FRAME, Figma toggle ile preview**

Semantic Colors collection zaten **mode-aware**. Frame Light fill'leriyle (ve tüm bound variable'larla) oluşturulduğunda, kullanıcı Figma'da \`Semantic Colors (S Theme)\` dropdown'undan **Auto/Light/Dark** arasında **preview** eder. İki ayrı frame YAYGIN OLARAK GEREKMEZ.

**Kural:**
- **Default (kullanıcı sadece "ekran yap" dedi):** Tek frame üret, Light mode'da bıraj. Kullanıcı Dark'ı Figma UI'dan görebilir.
- **Clone YAP — SADECE şu durumlarda:**
  - Kullanıcı explicit "Light + Dark iki ayrı frame" istedi
  - Deliverable "Light + Dark yan yana karşılaştırma" gerektiriyor (spec dokümanı, handoff)

**Clone gerektiğinde uygulama:**
\`\`\`js
// tokens.md "Collection Info" — cache'ten hazır:
// Semantic Colors collectionKey: 6041ac29aa893c975d9e5da4a5f4cf5a3e5d65e1
// Light modeId: 3015:2  |  Dark modeId: 3019:3

const coll = await figma.variables.importVariableCollectionByKeyAsync("6041ac29aa893c975d9e5da4a5f4cf5a3e5d65e1");
const darkFrame = lightFrame.clone();
darkFrame.setExplicitVariableModeForCollection(coll.id, "3019:3");
// fill rebind YOK, variable swap YOK, ayrı component import YOK.
\`\`\`

YASAK:
- Kullanıcı istemeden Dark klonu oluşturma (Figma toggle zaten var)
- Tek tek fill'leri Dark'a yeniden bağlama
- "Dark" isimli token arama — mode collection zaten işi yapıyor

**3. COMPONENT vs COMPONENT_SET — Doğru Import API (v3.1.5+ Phase H — KRİTİK):**

Figma Plugin API'de iki ayrı import fonksiyonu var:
- \`figma.importComponentByKeyAsync(key)\` → **sadece tekil COMPONENT** için. SET key verirsen **"Could not find a published component with the key"** hatası alırsın (yanıltıcı hata mesajı — gerçek sebep yanlış API kullanımı).
- \`figma.importComponentSetByKeyAsync(key)\` → **COMPONENT_SET (variant'lı)** için. Dönen \`ComponentSetNode\`'u \`.defaultVariant.createInstance()\` ile instance yap, sonra \`setProperties()\` ile variant seç.

**Kural:** \`figma_get_library_components\` response'u her item'da \`kind: "COMPONENT" | "COMPONENT_SET"\` field döner. Ayrıca top-level \`componentSetKeys: string[]\` ve gerekirse \`_warnings: ["COMPONENT_SET_KEYS: ..."]\` verir.

\`\`\`js
// DOĞRU pattern (kind'a göre dallan):
if (item.kind === "COMPONENT_SET") {
  const set = await figma.importComponentSetByKeyAsync(item.key);
  const inst = set.defaultVariant.createInstance();
  inst.setProperties({ "Type": "primary", "State": "default" });
} else {
  const comp = await figma.importComponentByKeyAsync(item.key);
  const inst = comp.createInstance();
}
\`\`\`

**YASAK:** Variant'lı component'e (Button, NavigationTopBar, Badge vb.) \`importComponentByKeyAsync\` çağırmak. Daima \`item.kind\` kontrol et.

**4. Multi-Library Subscription (v3.1.4+ Phase G):**

SUI ekosistemi tek library değil — \`❖ SUI\` (ana) + \`❖ SUI Mobil\` (mobil UI) + başkaları. Her component belirli bir library'de yayımlanmıştır; \`importComponentByKeyAsync(key)\` hedef Figma dosyasının **ilgili library'yi subscribe etmiş olması** durumunda çalışır.

**Kaynak:** \`figma_get_library_components\` response'u her item'da \`sourceLibrary\` (örn. \`❖ SUI Mobil\`) field'ı döner. Ayrıca top-level \`requiredLibraries: string[]\` ve gerekirse \`_warnings: ["REQUIRED_LIBRARIES: ..."]\` verir.

**Kural — ilk figma_execute öncesi kontrol:**
1. \`figma_get_library_components\` response'undan \`requiredLibraries\` oku
2. Eğer \`requiredLibraries.length > 1\` (yani mobil + ana gibi birden çok library) → kullanıcıya **onay sorusu sor**:
   > *"Bu ekran için \`❖ SUI\` ve \`❖ SUI Mobil\` library'lerinin ikisi de subscribe olmalı. Figma'da Assets panelini açıp her ikisinin enabled olduğunu onaylar mısınız?"*
3. Onay geldikten sonra üretime geç.

**importComponentByKeyAsync fail ederse** (\`Could not find a published component with the key\`):
- Component'in item'ına bak → \`sourceLibrary\` değeri ne?
- Kullanıcıya **kesin olarak** söyle: *"\`<component name>\` \`<sourceLibrary>\` library'sinde. Assets → Libraries → \`<sourceLibrary>\`'yi enable edin, sonra tekrar deneyin."*
- YASAK: fallback olarak \`figma_search_assets\` ile aynı component'i başka yerden aramak — key zaten scope'lu, boşuna denenir.

**4. LIBRARY_MISMATCH error handling:**
Server tool \`_warnings: ["LIBRARY_MISMATCH"]\` dönerse (user istediği library ≠ active.md'dekiyle):
- Kullanıcıya: *"active-ds.md'deki library \`<ctx.libraryName>\` olarak kayıtlı, siz \`<requested>\` dediniz. Hangisini kullanayım?"*
- Yanıta göre \`~/.claude/data/fcm-ds/active.md\`'yi güncellemek için \`/ds-select\` komutunu öner.
- YASAK: sessizce farklı library'ye geçmek, başka file'ları taramak.

**Token hedefi:** Cache hit'te bir ödeme/login/form ekranı **≤8 tool call** total (variable cache + component cache + 1 runtime text style discovery + 2-3 execute + validate).

**\`_nextStepObj\` izleme (v2.0+ — server-driven sequencing):** Her \`figma_*\` tool response'unda \`_nextStepObj: { tool, args_hint?, reason }\` alanı varsa, agent BİR SONRAKİ tool'u bu öneriden çağırır. Kullanım akışı:

\`\`\`
response.json.parse → _nextStepObj varsa →
  next_tool_name = obj.tool
  next_args = obj.args_hint  (opsiyonel override)
  rationale = obj.reason  (kullanıcıya/rapora yaz)
→ tool çağır
\`\`\`

Server cache zincirinde otomatik sequencing: \`figma_resolve_active_ds\` (fresh) → \`_nextStepObj: figma_get_library_components\` → \`_nextStepObj: figma_get_library_tokens\` → \`_nextStepObj: figma_execute\`. Agent karar ağacını her call'da yeniden yürütmez — server seqüans gönderir.

**Backward compat:** Legacy \`_nextStep\` string alanı hâlâ mevcut (v1.9.7+); \`_nextStepObj\` yoksa agent klasik karar ağacına düşer. İki alan bir arada ise **objeyi tercih et**.

### Adım 0 — DS GATE (Cache MISS yolu)

\`\`\`
1. Read(".claude/design-systems/active-ds.md")
2. ✅ Aktif → Library Name not al, devam
   ❌ Seçilmedi veya dosya yok → DUR, kullanıcıya "Hangi DS?" sor, hiçbir figma_* çağırma
\`\`\`

DS belirsizken \`figma_get_file_data\`, \`figma_search_assets\` çağırmak YASAK. İstisnalar: \`figma_get_status()\`, filesystem read, Claude vision.

### Adım 0.5 — Fast Path Check

5 koşulun HEPSİ TRUE → \`fmcp-screen-recipes\` Read, recipe uygula:
1. Tek ekran (multi-screen değil)
2. Standart tip (login/payment/profile/list/detail/form/onboarding/dashboard/settings)
3. DS aktif
4. Platform belli (explicit keyword VEYA önceki intent'ten saved). Yoksa DUR, kullanıcıya sor. Default varsayım YASAK.
5. Animation/prototype YOK

Biri bile FALSE → Karar Akışı'na geç. Recipe kırılırsa da fallback.

### Karar Akışı

\`\`\`
1. Intent net mi? EVET → sub-skill / HAYIR → Read fmcp-intent-router
2. image/figma_benchmark → Read inspiration-intake → structural_intent JSON
3. figma_execute yazacak mı? EVET → Read figma-canvas-ops
4. Ana motor → Read generate-figma-screen
5. build-from-scratch vs clone-to-device
\`\`\`

### DS Fallback Chain

1. **DS component instance** — en çok tercih
2. **DS primitive variant** — yakın variant + setProperties
3. **Token-bound primitive** — createFrame + tüm fill/padding/radius variable'a bağlı → meşru, ihlal DEĞİL
4. **Hardcoded shape** → GERÇEK İHLAL, DUR, kullanıcıya bildir

### Resmi Figma MCP Yasağı

\`Figma:*\` prefix'li tool'lar (mcp.figma.com) ASLA çağrılmaz. Sadece \`figma_*\` (figma-mcp-bridge) kullan. \`figma_search_assets\` boş → Rule 24 fallback (manuel instance scan), \`Figma:search_design_system\`'e düşME.

### Filesystem MCP

Skill Read için: \`mcp__fmcp-filesystem__read_text_file(path="<absolute_path>/skills/<skill>/SKILL.md")\`. Claude Desktop'ta prompt'ta absolute path belirtilmeli.

### Self-Audit Gate + Verification

\`\`\`
figma_validate_screen(nodeId=<wrapper_id>, minScore=80)
\`\`\`
- \`<80\` → SEVERE violation'ları oku, düzelt, yeniden validate
- 3 deneme fail → kullanıcıdan rebuild onayı al

Teslim öncesi kontrol: validate ≥80, ham shape yok, tüm değerler token'a bağlı, auto-layout eksiksiz, Türkçe rapor + metrikler.

### Rapor Formatı

\`\`\`markdown
## 🎨 Ekran Üretimi — <ekran_adı>
**Mod:** <intake_mode> | **DS:** <active-ds> | **Yaklaşım:** <approach>
### Sonuç
<Figma node link>
📊 Metrikler: skill'ler, API çağrı, cache hit/miss, execute sayısı, validate score
\`\`\`

---

---

<!-- figma-canvas-ops (2565 tokens) -->
---
name: figma-canvas-ops
description: F-MCP Bridge ile Figma tuvalinde güvenli yazma/düzenleme için zorunlu önkoşul kılavuzu. figma_execute çağrısı öncesi bu skill yüklenmelidir.
metadata:
  mcp-server: user-figma-mcp-bridge
  personas:
    - designer
    - designops
---

# Figma Canvas Ops — figma_execute Güvenli Kullanım Kılavuzu

## Araç Eşleme (topluluk → F-MCP)

| Topluluk | F-MCP Bridge | Not |
|---|---|---|
| \`use_figma\` | \`figma_execute\` | JS çalıştırma |
| \`get_metadata\` | \`figma_get_file_data\` | Yapı/metadata |
| \`get_screenshot\` | \`figma_capture_screenshot\` | Görsel doğrulama |
| \`search_design_system\` | \`figma_search_components\` + \`figma_get_design_system_summary\` | İki araç birlikte |

## Prerequisites

- F-MCP Bridge plugin bağlı olmalı (\`figma_get_status()\`)
- Aktif DS context: \`.claude/design-systems/active-ds.md\` → \`Status: ✅\`

> **🔒 FMCP Cache Resolve (v3.1+ — İLK YOL):**
> Cache okuma için Claude'un filesystem'a bakması GEREKMEZ. Server tool'ları kullan:
> - \`figma_resolve_active_ds()\` — active library + cache status (\`fresh\`/\`stale\`/\`missing\`)
> - \`figma_get_library_components(libraryName)\` — componentKey listesi
> - \`figma_get_library_tokens(libraryName)\` — variableKey listesi
>
> Cache hit'te **0 Plugin API call**, cross-file çalışır. Cache miss'te \`_restFallbackHint\` döner → Rule 24.1+ fallback chain'e düş.
> **Token hedefi:** ödeme/login ekranı ≤6 tool call total.

## 0. Design System Context (ZORUNLU)

### 0a — Active DS check
\`\`\`
1. ÖNCE figma_resolve_active_ds() — server cache (v3.1+)
   ✅ "fresh" → Library Name + cache status not al, 0b'ye geç
   ⚠️ "stale" → Library Name not al ama klasik fallback'e hazır ol
   ❌ "missing" → Aşağıdaki klasik akışa düş

2. Klasik akış (cache miss): Read .claude/design-systems/active-ds.md
3. ✅ Aktif → Library Name not al, 0b'ye geç
   ❌ Seçilmedi → 0c'ye geç
   "DS bypass mode" → DS'siz devam
\`\`\`

### 0b — DS asset cache hazırlığı
\`\`\`
1. .claude/design-systems/<library-id>/components.md var mı?
2. .claude/design-systems/<library-id>/tokens.md var mı?
3. Yoksa: figma_get_library_variables + figma_search_assets ile keşfet, cache'e yaz
\`\`\`

### 0c — Kullanıcıya DS seçimi sor
active-ds.md \`❌\` ise: "Hangi DS? (SUI / Material / HIG / Kendi / Hiçbiri)". Yanıt sonrası active-ds.md güncelle, 0b'ye geç. Sonraki turlarda TEKRAR SORMA.

## 1. Kritik Kurallar

1. **\`return\` ile veri dön.** \`figma.closePlugin()\` çağırma.

2. **Düz JS, top-level \`await\`.** Kod otomatik async sarılır. \`(async()=>{})()\` sarma. **Async API zorunlu** — dynamic-page mode'da sync API'ler throws:

   | ❌ YASAK (sync) | ✅ ZORUNLU (async) |
   |---|---|
   | \`instance.mainComponent\` | \`await instance.getMainComponentAsync()\` |
   | \`figma.getNodeById(id)\` | \`await figma.getNodeByIdAsync(id)\` |
   | \`figma.variables.importVariableByKey(key)\` | \`await figma.variables.importVariableByKeyAsync(key)\` |
   | \`figma.importComponentByKey(key)\` | \`await figma.importComponentByKeyAsync(key)\` |
   | \`figma.importStyleByKey(key)\` | \`await figma.importStyleByKeyAsync(key)\` |
   | \`node.effectStyleId = x\` | \`await node.setEffectStyleIdAsync(x)\` |
   | \`node.textStyleId = x\` | \`await node.setTextStyleIdAsync(x)\` |
   | \`figma.listAvailableFonts()\` | \`await figma.listAvailableFontsAsync()\` |
   | \`figma.loadFont(...)\` | \`await figma.loadFontAsync(...)\` |
   | \`figma.variables.getVariableCollectionById(id)\` | \`await figma.variables.getVariableCollectionByIdAsync(id)\` |
   | \`figma.root.findAll()\` / \`page.findAll()\` | **Önce** \`await figma.loadAllPagesAsync()\` (v2+ Plugin API gereksinimi). Tek sayfa traversal için \`await figma.currentPage.loadAsync()\` yeterli. \`findAll\` çağrıldığında page explicit yüklü değilse runtime error. |

3. **\`figma.notify()\` çalışmaz** — kullanma.

4. **\`console.log()\` dönmez** — \`return\` kullan.

5. **Küçük adımlarla çalış.** Timeout: varsayılan 15000ms, max 30000ms.

   ### 5a. CHUNKING MANDATE (v2.0)

   Her \`figma_execute\` **max 15 atomic operation**. Atomic op'lar: node/instance oluşturma, variable/style/component import, font load, bind operasyonu, getNodeByIdAsync, getMainComponentAsync.

   - 1 execute = 1 mega-goal (discovery, frame+structure, 3-4 component placement)
   - 25+ op → 2-3 execute'a böl
   - Execute arası state: nodeId'leri \`return\` et, sonraki execute \`getNodeByIdAsync\` ile al
   - Her execute sonrası 1 satır Türkçe micro-report

6. **Renkler 0–1 aralığında** (0–255 değil). Hardcoded renk YASAK — DS'den oku.

7. **Fills/strokes read-only array** — klonla, değiştir, ata:
   \`\`\`js
   const fills = [...node.fills];
   fills[0] = { ...fills[0], color: DS_COLOR };
   node.fills = fills;
   \`\`\`

8. **Font yükleme zorunlu.** Sıra: (a) DS cache'ten font oku → (b) Yoksa kullanıcıya sor → (c) "Sen seç" → Inter.

   **8a-1) Font weight check (ZORUNLU):** \`loadFontAsync\` öncesi \`listAvailableFontsAsync\` ile kontrol et. Fallback helper:
   \`\`\`js
   const dsFontFamily = activeDS.fontFamily; // active-ds.md veya cache'ten dinamik oku — hardcoded font ismi YASAK
   const allFonts = await figma.listAvailableFontsAsync();
   const styles = allFonts.filter(f => f.fontName.family === dsFontFamily).map(f => f.fontName.style);
   function pickStyle(desired, available) {
     if (available.indexOf(desired) >= 0) return desired;
     var fb = { "Medium":["Semi Bold","Regular"], "ExtraBold":["Bold"], "Black":["Bold"], "Thin":["Light","Regular"] };
     var alts = fb[desired] || [];
     for (var i = 0; i < alts.length; i++) { if (available.indexOf(alts[i]) >= 0) return alts[i]; }
     return available.find(s => s.indexOf("Italic") < 0) || available[0];
   }
   await figma.loadFontAsync({ family: dsFontFamily, style: pickStyle("Medium", styles) });
   \`\`\`
   **FigJam:** \`createShapeWithText()\` varsayılan "Inter Medium". Metin düzenlemeden önce \`await figma.loadFontAsync(shape.text.fontName)\`.

   **Rule 8b-pre — Font Family Source (v2.0+ ZORUNLU):**

   \`loadFontAsync({ family })\` çağırmadan ÖNCE \`family\` değerini şu kaynaklardan sırayla dene:

   1. **Adım 1.6 çıktısı:** \`fontFamilies[0]\` — \`fmcp-screen-recipes\` Adım 1.6 session'da önceden çalıştıysa (recommended)
   2. **\`style.fontName.family\`:** \`getStyleByIdAsync\` sonucundan (library'den gelen style objesinde mevcut)
   3. **Fallback \`"Inter"\`:** ADVISORY warning zorunlu — log'a yaz: \`_warnings: ["FONT_FAMILY_FALLBACK_INTER"]\`

   YASAK: Hardcoded \`"Inter"\` family'yi doğrudan yazmak, DS'nin fontunu varsaymadan font load etmek. Yanlış family ile \`loadFontAsync\` + doğru family bekleyen \`setTextStyleIdAsync\` → silent mismatch (text görünmez veya default font'a düşer).

   **Rule 8b — Text Style + Font Ordering (v1.9.9+ ZORUNLU):**

   Library text style uygularken MUTLAK SIRALAMA:
   \`\`\`js
   const style = await figma.importStyleByKeyAsync(textStyleKey);   // 1. import
   await figma.loadFontAsync(style.fontName);                        // 2. font load
   await textNode.setTextStyleIdAsync(style.id);                     // 3. style apply
   \`\`\`

   ❌ YANLIŞ: \`setTextStyleIdAsync\` önce, \`loadFontAsync\` sonra → runtime error ("font not loaded").
   ❌ YANLIŞ: \`loadFontAsync({family: "Inter"})\` ama style'ın gerçek fontu farklı → silent mismatch, text render'ı beklenmedik.

   Default font (Inter vb., text style olmadan):
   \`\`\`js
   await figma.loadFontAsync({ family: "Inter", style: "Regular" });  // ÖNCE
   textNode.fontName = { family: "Inter", style: "Regular" };         // SONRA
   \`\`\`

9. **Sayfa konteksti her çağrıda sıfırlanır.** Farklı sayfa: \`await figma.setCurrentPageAsync(page)\`.

10. **Tüm tasarım değerleri DS variable'a BAĞLANMALI (ZORUNLU).**

    Renk, spacing, padding, radius — HİÇBİR değer hardcoded yazılmaz. Token yoksa DURDUR, kullanıcıya sor.

    **Akış:**
    - **Variable import:** \`const v = await figma.variables.importVariableByKeyAsync("KEY")\`
    - **Renk bind:** \`node.fills = [figma.variables.setBoundVariableForPaint(fills[0], "color", v)]\`
    - **Spacing bind:** \`node.setBoundVariable("paddingLeft", v)\`
    - **Text style:** \`await textNode.setTextStyleIdAsync(style.id)\`
    - **Text renk:** \`textNode.fills = [figma.variables.setBoundVariableForPaint(textFills[0], "color", textColorVar)]\`

    Hardcoded \`node.fills = [{ type: "SOLID", color: {...} }]\` YASAK.

10a. **Inline Bind Verification (v1.9.4, ZORUNLU).** Her execute sonunda oluşturulan node'ları tara. Bind eksikse \`throw\` atılır — execute başarısız sayılır, Claude retry eder. Şablon:

    \`\`\`js
    // Execute'un sonunda, createdNodes listesini tarayıp bind kontrolü yap:
    function assertBound(node) {
      // Fill bind
      if (Array.isArray(node.fills)) {
        for (var i = 0; i < node.fills.length; i++) {
          var f = node.fills[i];
          if (f && f.visible !== false && f.type === "SOLID") {
            var fbv = node.boundVariables && node.boundVariables.fills;
            var bound = fbv && (Array.isArray(fbv) ? fbv[i] : true);
            if (!bound) throw new Error("UNBOUND_FILL: " + node.name + " — setBoundVariableForPaint cagrisi eksik");
          }
        }
      }
      // Padding/itemSpacing/radius bind (auto-layout frame)
      if (node.type === "FRAME" || node.type === "COMPONENT") {
        var padProps = ["paddingTop","paddingBottom","paddingLeft","paddingRight"];
        for (var j = 0; j < padProps.length; j++) {
          var p = padProps[j];
          if (typeof node[p] === "number" && node[p] > 0 && !(node.boundVariables && node.boundVariables[p])) {
            throw new Error("UNBOUND_PADDING: " + node.name + "." + p + "=" + node[p] + " — setBoundVariable cagrisi eksik");
          }
        }
        if (typeof node.itemSpacing === "number" && node.itemSpacing > 0 && !(node.boundVariables && node.boundVariables.itemSpacing)) {
          throw new Error("UNBOUND_ITEMSPACING: " + node.name + " — setBoundVariable('itemSpacing', v) cagrisi eksik");
        }
        var radProps = ["cornerRadius","topLeftRadius","topRightRadius","bottomLeftRadius","bottomRightRadius"];
        for (var k = 0; k < radProps.length; k++) {
          var r = radProps[k];
          if (typeof node[r] === "number" && node[r] > 0 && !(node.boundVariables && node.boundVariables[r])) {
            throw new Error("UNBOUND_RADIUS: " + node.name + "." + r + "=" + node[r]);
          }
        }

---

<!-- fmcp-screen-recipes (2126 tokens) -->
---
name: fmcp-screen-recipes
description: Fast path cookbook — standart ekran tipleri (login/payment/profile/list/detail/form/onboarding/dashboard/settings) için 5 mega-adımlı recipe. Max 15 op/execute, cache-first discovery, her adımda Türkçe micro-report.
metadata:
  mcp-server: user-figma-mcp-bridge
  version: 3.0.0
  priority: 96
  phase: fast-path
  personas:
    - designer
    - uidev
  token_budget: condensed-first
required_inputs:
  - name: screen_type
    type: "enum: login | payment | profile | list | detail | form | onboarding | dashboard | settings"
  - name: platform
    type: "enum: mobile | tablet | desktop | web"
  - name: device_preset
    type: string
  - name: variants
    type: "array: [light] | [light, dark]"
  - name: active_ds
    type: string
outputs:
  - name: light_frame_id
    type: string
  - name: dark_frame_id
    type: "string | null"
  - name: validate_scores
    type: "{ light: number, dark: number | null }"
---

# FMCP Screen Recipes — Fast Path Cookbook

> **Kullanım (v3.1+):** \`fmcp-screen-orchestrator\` Adım 0.5 Fast Path 5/5 match olduğunda çağrılır. Bağımsız giriş noktası değil. Adım 1.6 (Text Style Resolution) canonical kopyası burada — orchestrator buraya referans verir, kod duplicate etmez.

## Ne Zaman Kullanılır

**Fast Path DEVREYE GİRER** (hepsi TRUE olmalı):
- ✅ Tek ekran üretimi
- ✅ Standart ekran tipi: 9 recipe'ten biri match ediyor
- ✅ DS tanımlı: \`active-ds.md\` Status: ✅ Aktif
- ✅ Platform belli
- ✅ Custom animation / prototype YOK

**Devreye GİRMEZ:** Multi-screen flow, custom layout, animation, explicit generate-figma-screen talebi, DS GATE geçilmemişse.

---

## 5 Mega-Adımlı Akış

Max **15 op/execute**. Her mega-adım sonrası tek satır Türkçe micro-report.

\`\`\`
M1: Pre-Flight Discovery + Token + Text Style  (1 execute, ~15 op)
M2: Frame + Structure + Modes                   (1 execute, ~12-14 op)
M3: Component Placement (toplu, 3-4/execute)    (2-3 execute, ~12-15 op each)
     ↳ Her M3 execute sonrası: figma_scan_ds_compliance(threshold=85) inline gate
M4: Dark Variant                                (1 execute, ~4 op)
M5: Validate + Final Report                     (ZORUNLU: figma_scan_ds_compliance(detailed) + figma_validate_screen)
\`\`\`

**Toplam execute:** ~6-8 + 2-3 scan call. **Hedef süre:** ~10 dk. **v1.9.4:** Scan call'ları hızlıdır (~150ms), execute bütçesini yemezler.

### 3 MUTLAK KURAL

**KURAL 1 — Fill Bind Zorunlu (frame + text dahil):**
\`\`\`js
const paint = { type: 'SOLID', color: { r: 1, g: 1, b: 1 } };
const bound = figma.variables.setBoundVariableForPaint(paint, 'color', dsColorVar);
node.fills = [bound];
\`\`\`
Fill panel'de variable icon 🎨 GÖRÜNMELI. Hardcoded hex YASAK. Frame fill + text fill + primitive dahil TÜM node'lar.

**KURAL 2 — Variant Seçim: DEFAULT Koru:**
- \`setProperties\` ile SADECE recipe'de explicit belirtilen property'leri set et
- Diğer TÜM property'leri DEFAULT bırak
- \`Product\` → main (default), Boolean kontroller → recipe'de explicit yoksa DEFAULT

**KURAL 3 — Token Bind, Alias Resolve ETME:**
\`setBoundVariable(property, importedVariable)\` ile bind et. Figma runtime alias chain'i otomatik çözer. \`valuesByMode\` okuma, alias traversal YASAK (timeout riski).

### Mega-Adım Mapping

Aşağıdaki eski adımlar REFERANS amaçlıdır. AYRI AYRI execute ETME — mega-adım tablosunu takip et:
- **M1:** Adım 1 (validation) + 1.5 (discovery) + 1.6 (text style) → TEK execute
- **M2:** Adım 2 (frame) + 4b (mode) + 5.5 (content body) → TEK execute
- **M3:** Adım 6 (discovery) + 7 (placement) → 2-3 execute
- **M4:** Adım 8 (dark) → TEK execute
- **M5:** Adım 9 (validate) → 1-2 validate call

---

### Adım 1 — Pre-Flight Check

Hiçbir figma_execute çağırma. Doğrula: active-ds.md ✅, screen_type geçerli, platform + device_preset geçerli, variants ≥1.

**Micro-report:** \`✅ Pre-flight: screen_type=<X>, platform=<Y>, device=<Z>, variants=<V>\`

### Adım 1.5 — Unified Pre-Flight Discovery

**Cache-First (v3.0+):** Önce \`.claude/design-systems/<active-ds>/tokens.md\` oku (\`<active-ds>\` = \`active-ds.md\`'den \`Library Name\`'in slug hali — \`❖ SUI\` → \`sui\`, \`Material\` → \`material\`, vb.). Cache varsa ve <7 gün → token discovery ATLA, cache'ten kullan. Yoksa aşağıdaki execute'ları çalıştır, sonra cache'i güncelle.

Token name matching: DS nested path formatı (örn. \`"Spacing/spacing-100"\`). \`endsWith\` match kullan:
\`\`\`js
vars.find(v => v.name.endsWith("/" + suffix) || v.name === suffix)
\`\`\`

#### Execute 1 — Collection & Mode Discovery (7 op)

\`\`\`js
const colls = await figma.teamLibrary.getAvailableLibraryVariableCollectionsAsync();
function findColl(keywords) {
  return colls.find(c => {
    const n = c.name.toLowerCase().trim();
    return keywords.some(kw => n.includes(kw));
  });
}
const sizeColl = findColl(["semantic size", "semantic sizes", "size"]);
const colorsColl = findColl(["semantic color", "s theme"]);
const result = { availableColls: colls.map(c => ({name: c.name, key: c.key})), spacingTokenKeys: {}, collectionInfo: { colors: null, size: null }, surfaceKey: null };

if (sizeColl) {
  const sizeVars = await figma.teamLibrary.getVariablesInLibraryCollectionAsync(sizeColl.key);
  const suffixes = ["spacing-none","spacing-050","spacing-075","spacing-100","spacing-125","spacing-150","spacing-200"];
  for (const s of suffixes) {
    const f = sizeVars.find(v => v.name.endsWith("/"+s) || v.name === s);
    if (f) result.spacingTokenKeys[s] = f.key;
  }
  if (sizeVars.length > 0) {
    const first = await figma.variables.importVariableByKeyAsync(sizeVars[0].key);
    const coll = await figma.variables.getVariableCollectionByIdAsync(first.variableCollectionId);
    result.collectionInfo.size = { collId: coll.id, modes: coll.modes.map(m => ({name: m.name, modeId: m.modeId})) };
  }
}
if (colorsColl) {
  const colorsVars = await figma.teamLibrary.getVariablesInLibraryCollectionAsync(colorsColl.key);
  const bgVar = colorsVars.find(v => v.name.toLowerCase().includes("background") && v.name.toLowerCase().includes("level-0"));
  if (bgVar) result.surfaceKey = bgVar.key;
  if (colorsVars.length > 0) {
    const first = await figma.variables.importVariableByKeyAsync(colorsVars[0].key);
    const coll = await figma.variables.getVariableCollectionByIdAsync(first.variableCollectionId);
    result.collectionInfo.colors = { collId: coll.id, modes: coll.modes.map(m => ({name: m.name, modeId: m.modeId})) };
  }
}
return result;
\`\`\`

#### Execute 2 — Critical Token Import (7 op)

\`\`\`js
const tokenKeyMap = {};
const spacingKeys = { /* Execute 1'den gelen spacingTokenKeys */ };
for (const [suffix, key] of Object.entries(spacingKeys)) {
  try {
    const imported = await figma.variables.importVariableByKeyAsync(key);
    tokenKeyMap[suffix] = imported.id;
  } catch(e) {}
}
return { tokenKeyMap };
\`\`\`

**Micro-report:** \`✅ Pre-Flight Discovery: <N> collection, <M> token imported, surface=<found/missing>\`

### Adım 1.6 — Text Style Resolution (v2.0+ — fontFamilies + seed fallback)

Dosyadaki mevcut text style'ları tara, role mapping + font family üret. \`importStyleByKeyAsync\` ÇAĞIRMA — direkt \`setTextStyleIdAsync(roleMap[role].id)\` kullan.

\`\`\`js
// Adım A: Sayfa boşsa ilk componentKey ile seed instance düşür (v2.0+ Page 4 senaryosu)
// Caller \`seedComponentKey\` değişkenini opsiyonel olarak tanımlar (componentKey cache'ten).
// Tanımsızsa sessizce skip edilir — styleMap boş dönebilir, fallback chain devreye girer.
let seedInst = null;
if (figma.currentPage.findAll(n => n.type === "TEXT").length === 0) {
  const _seedKey = (typeof seedComponentKey !== "undefined") ? seedComponentKey : null;
  if (_seedKey) {
    try {
      const seedComp = await figma.importComponentByKeyAsync(_seedKey);
      seedInst = seedComp.createInstance();
      figma.currentPage.appendChild(seedInst);
    } catch(e) { /* fallback: keep going, styleMap may be empty */ }
  }
}

// Adım B: findAll + getStyleByIdAsync
const allTexts = figma.currentPage.findAll(n => n.type === "TEXT");
const uniqueStyleIds = new Set();
for (const t of allTexts) { if (t.textStyleId && typeof t.textStyleId === 'string') uniqueStyleIds.add(t.textStyleId); }

const styleMap = {};
const fontFamilySet = new Set();
for (const id of uniqueStyleIds) {
  try {
    const style = await figma.getStyleByIdAsync(id);
    if (style) {
      styleMap[style.id] = { id: style.id, name: style.name, fontSize: style.fontSize || null, fontName: style.fontName || null };
      if (style.fontName?.family) fontFamilySet.add(style.fontName.family);  // v2.0+
    }
  } catch(e) {}
}

---

<!-- fmcp-project-rules (1662 tokens) -->
---
name: fmcp-project-rules
description: F-MCP Bridge kullanım kuralları — Design Token Kuralı, Bağlı Token Kuralı, kütüphane yönetimi, otomatik yanıt kuralları. Tüm F-MCP skill'leri için geçerli temel kurallar. Her Figma işleminde bu kurallar otomatik olarak geçerlidir.
metadata:
  mcp-server: user-figma-mcp-bridge
  personas:
    - designer
    - designops
    - uidev
    - po
---

# F-MCP Temel Kurallar

Bu skill, tüm F-MCP skill'leri ve komutları için geçerli olan temel kuralları tanımlar. Her Figma işleminde bu kurallar otomatik olarak uygulanır.

## Kullanıcı İstekleri — Otomatik Yanıt

### "F-MCP'yi güncelle" / "update" / "güncelle"
Terminal komutu verme. \`bash scripts/update.sh\` çalıştır, sonucu bildir:
> Güncelleme tamamlandı (vX.Y.Z). Claude'u yeniden başlat ve Figma'da plugin'i kapat-aç.

### "F-MCP'yi kur" / "setup" / "kur" / "bunu kur" / GitHub linki verildi
Kullanıcı GitHub linki (github.com/atezer/FMCP) verip "kur" derse veya herhangi bir şekilde kurulum isterse:

1. Repo zaten clone edilmişse: \`bash scripts/setup.sh\` çalıştır
2. Repo clone edilmemişse: \`git clone https://github.com/atezer/FMCP.git && cd FMCP && bash scripts/setup.sh\`
3. Kullanıcıya sadece sonucu bildir.

Kullanıcıya ASLA terminal komutu söyleme, teknik adım açıklama. Her şeyi sen yap.

### Dil
Kullanıcı Türkçe konuşuyor. Tüm dosyalarda Türkçe karakterler (ş, ç, ğ, ö, ü, ı, İ) doğru kullanılmalı.

---

## Token-Only Enforcement (v1.9.8+ MUTLAK)

**Kullanıcıya soru/seçenek sunarken** (AskUserQuestion options, plan summary, onay metni, fallback dialog):

- ❌ **YASAK:** ham hex değer (\`#195e90\`, \`#FFFFFF\`), ham px (\`375px\`, \`390px\`), ham pt, ham rem, ham RGB
- ✅ **ZORUNLU:** token adı (\`<DS>/primary/default\`, \`<DS>/spacing/150\`, \`<DS>/text/body/M\`)
- ✅ **ZORUNLU:** device preset adı (\`iPhone 17 (402×874)\`, \`Pixel 8 Pro (412×917)\`, \`iPad Pro 11 (834×1194)\`)

**Self-check (ZORUNLU):** \`AskUserQuestion\` çağırmadan önce soru metnini ve tüm option text'lerini kontrol et:
- Regex match: \`/#[0-9a-f]{3,8}\\b/i\` → **VARSA:** soru kuralı ihlali, hex'i \`<DS>/...\` token adıyla değiştir ve yeniden formüle et
- Regex match: \`/\\b\\d{2,4}\\s*px\\b/i\` → **VARSA:** px yerine device preset adı veya \`<DS>/spacing/...\` kullan

**Gerekçe:** Kullanıcı hex/px görmemeli — token adı DS-agnostic, DS değiştiğinde soru otomatik doğru kalır. Hex sunmak "Option A vs B" gibi sahte alternatifler üretir ve kullanıcıyı DS dışına çıkarır.

**Tek istisna:** Kullanıcı açıkça "hex değeri göster" isterse debug/troubleshooting bağlamında gösterilebilir, ama UI seçim option'ı olarak DEĞİL.

---

## Design System Kütüphaneleri

Kullanıcı lokal olarak design system kütüphaneleri kaydedebilir. Kayıtlı kütüphaneler \`.claude/libraries/\` dizininde bulunur.

### Kullanım kuralları

1. **Skill çalıştırmadan önce** \`.claude/libraries/\` dizinini kontrol et. Kayıtlı kütüphane varsa oku.
2. **Varsayılan kütüphane:** Kullanıcı "hangi kütüphane?" demişse veya context'ten anlaşılamıyorsa, kayıtlı kütüphanelerden ilkini kullan.
3. **Figma file key'leri** kütüphane dosyasındaki tablolardan al — URL'den parse etme, doğrudan \`File Key\` alanını kullan.
4. **Token okuma** her zaman kütüphanenin WEB/ana dosyasından yapılır.
5. **Platform seçimi:** Web ekranı → WEB dosyası, Mobil ekran → Mobil dosyası (yoksa WEB fallback).

---

## Design Token Kuralı (TÜM skill'ler için geçerli — ZORUNLU)

Hiçbir skill gömülü/hardcoded design token değeri içeremez ve kullanamaz. Font ailesi, renk kodu, font boyutu, spacing, radius, gölge — hiçbir tasarım değeri skill içine yazılmaz.

**Her tasarım değeri çalışma anında tasarım sisteminden okunur:**

1. **Önce kayıtlı kütüphaneyi oku:** \`.claude/libraries/\` dizinindeki kütüphane dosyasını kontrol et. Font ailesi, variable collection'lar ve style listesi orada.
2. **Canlı değerleri Figma'dan al:**
   - **Kütüphane variable'ları (renkler, spacing)** → \`figma_get_library_variables()\` veya \`figma_execute\` ile \`figma.teamLibrary.getAvailableLibraryVariableCollectionsAsync()\` + \`getVariablesInLibraryCollectionAsync()\` — DS dosyasına bağlanmak GEREKMEZ, hedef dosyadan çalışır
   - **Lokal variable'lar** → \`figma_get_variables()\` — sadece dosya içi değerler
   - **Lokal stiller** → \`figma_get_styles()\` — sadece dosya içi stiller
   - **Kütüphane text style'ları** → cache'den key al, \`figma.importStyleByKeyAsync(key)\` ile import et. Cache yoksa REST API: \`figma_rest_api GET /v1/files/{fileKey}/styles\`
   - Font → kütüphane text style'larından veya kütüphanenin \`Font Ailesi\` alanından
   - Gölgeler → \`figma_get_styles()\` effect style'larından veya kütüphane cache'inden
3. **Bulunamazsa kullanıcıya sor.**
4. **Kullanıcı "sen seç" derse:** Önce DS kütüphanesi bağlıysa DS fontunu kullan (text style'lardan çıkar). DS fontu bulunamadıysa \`Inter\`, renkler için Figma varsayılanları kullan.

**ÖNEMLİ:** \`figma_get_styles()\` ve \`figma_get_variables()\` sadece dosya İÇİ (local) değerleri döndürür. Team library'den gelen token'lar için \`figma_get_library_variables\` veya \`figma.teamLibrary\` API'si kullanılmalıdır.

**Skill'lerdeki kod örnekleri:** Örneklerde geçen değerler (renk hex, font adı, piksel boyutu) yalnızca FORMAT gösterimidir. Çalışma anında bu değerler her zaman tasarım sisteminden okunmalıdır.

---

## Bağlı Token Kuralı (ZORUNLU — tüm ekran/bileşen oluşturma işlemlerinde)

Figma'da oluşturulan hiçbir node'da **bağlanmamış (unbound) tasarım değeri** bulunmamalıdır. Her renk, spacing, padding, radius ve metin stili DS variable'ına veya text style'ına **bağlı (bound)** olmalıdır.

- **Renk (fill/stroke):** \`figma.variables.importVariableByKeyAsync(key)\` ile import et, \`setBoundVariableForPaint()\` ile bağla
- **Spacing/padding/radius/gap:** \`setBoundVariable("paddingLeft", variable)\` ile bağla
- **Metin stili:** \`setTextStyleIdAsync(styleId)\` ile DS text style'ını uygula
- **Metin rengi:** Text node fill'ini \`setBoundVariableForPaint()\` ile bağla

**Hardcoded değer kabul edilmez.** \`node.fills = [{ type: "SOLID", color: {r,g,b} }]\` veya \`node.fontSize = 16\` gibi doğrudan değer atamaları YASAKTIR. Tüm değerler DS'ten import edilip bağlanmalıdır.

Detaylı API kullanımı: \`figma-canvas-ops\` skill'inin **madde 10** bölümüne bak.

---

## Mevcut kütüphaneler

Kayıtlı kütüphaneleri görmek için \`.claude/libraries/\` dizinini kontrol et. Her \`.md\` dosyası bir kütüphanedir. Kütüphane eklemek için \`/add-library\` komutunu kullan.

## Evolution Triggers

- Yeni DS kural kategorisi eklendiğinde bu skill güncellenmelidir.
- Yeni platform desteği (Flutter, React Native vb.) eklendiğinde platform seçimi kuralları genişletilmelidir.
- Kullanıcı geri bildirimine göre otomatik yanıt kuralları güncellenmelidir.`;

export const EMBEDDED_SKILLS_TOKEN_ESTIMATE = 12940;
export const EMBEDDED_SKILLS_VERSION = "1.9.7";
export const EMBEDDED_SKILLS_GENERATED_AT = "2026-04-21T13:08:57.193Z";
